server/db/models/cart.js
server/db/models/flowers.js
server/db/models/index.js
server/db/models/user.js

added new models

---

server/db/models/flowers.js

add flower model description and price

---

script/seed.js
server/db/models/user.js

Updated the seed file with seeding data

created seed data

---

server/api/flowers.js

add single flower route

---

client/components/flower-single.js
client/store/flowers.js

getting single flower up and running

---

client/components/flower-list.js
client/components/flower-single.js

single flower now working

---

server/api/flowers.js
server/api/flowers.spec.js
server/api/users.spec.js
server/db/models/cart.spec.js
server/db/models/flower.js
server/db/models/flower.spec.js
server/db/models/user.spec.js

added tests for api routes and models, updated cart and flower models

---

public/style.css

test for desi

---

public/index.html

undo merge conflict demo

---

public/index.html

conflict demo complete - fix

---

client/app.js
public/index.html
public/style.css

CSS and html page is no longer being covered by the perpetual cart feature.
We can now properly access the website features for our testing .
---

testable css

---

server/db/models/user.js

fix: add validation to address

---

server/api/cart.js
server/api/index.js

cart routes added

---

client/components/cart.js
client/components/checkout.js

chore: began work on checkout fix: edited total calculation on cart

---

server/db/models/index.js

fix: fix model index file

---

script/seed.js
server/db/models/index.js

updated model-index file and seed file

---

server/db/models/order.js

took quantity out of order model

---

server/db/models/index.js

corrected user to order relationship to one to many

---

server/db/models/index.js

corrected last model correction

---

client/components/cart-edit.js
client/components/cart.js

chore: update cart and cart-edit to display under cart

---

server/api/index.js

fix: api index file routes fixed

---

script/seed.js

added seed data for orders and orderFlowers

---

package-lock.json
script/seed.js
server/api/orders.js

added to orderFlower portion of seed

---

client/components/cart-edit.js
client/components/cart.spec.js
client/components/flower-single.spec.js
client/store/flowers.spec.js
package-lock.json
package.json
server/db/models/order.spec.js

chore: added two front end tests

---

client/components/auth-form.js
client/components/checkout.js
client/components/flower-single.js
client/store/user.js

chore: update auth and checkout forms, checkout is untested

---

client/components/cart-edit.js
client/components/cart.js
client/components/flower-single.js
client/store/orders.js

chore: updated cart, cart-edit, order component, and store-orders

---

client/components/auth-form.js

fix: removed extra  fields from dispatched log-in request

---

client/components/flower-list.js
client/components/navbar.js
public/style.css
server/api/routProtection.js

Say goodbye to the Kawasaki green and say hello so some Easter styling 
---

Feature: Css style

---

server/auth/index.js

fixed the login function

---

client/components/navbar.js
public/index.html
public/style.css

Updated styling for site

---

server/auth/google.js

chore: add serialize and deserialize to google.js / oauth

---

client/components/navbar.js
client/store/orders.js
server/auth/google.js

update: nav bar can clear state on logout

---

client/components/user-home.js
server/api/orders.js

backend of checkout now working

---

client/components/cart.js
client/components/checkout.js
client/components/guest-checkout.js
client/routes.js

chore: add guest-checkout component, edit routes, cart, and checkout

---

client/components/checkout.js
client/components/flower-single.js
client/components/guest-checkout.js
client/store/orders.js

update: checkout for guest an d user posts to db and clears session

---

client/components/user-home.js
client/store/user.js
server/api/users.js
server/auth/index.js

users can now update their own info

---

client/components/cart-edit.js
client/components/flower-single.js
client/store/orders.js
server/api/orders.js

fix: updated flower-single to add to db

---

client/components/flower-single.js
client/store/orders.js

chore: updated flower-single to add to db if user

---

client/components/order-list.js
client/components/user-home.js
client/store/orders.js
server/api/orders.js

set up back end and action creator for showing orders in user page

---

server/api/orders.js

fixed eager loading of past orders

---

client/components/cart-edit.js
client/components/flower-single.js
client/store/orders.js

chore: updates to persist cart in db

---

client/components/checkout.js
client/components/guest-checkout.js
client/store/orders.js
server/api/session.js

chore: updated checkout for user

---

client/components/order-list.js
client/components/user-home.js
public/style.css

now myAccount page is generating past orders

---

client/components/order-list.js

minor addition to order history in myAccout

---

client/components/user-home.js
server/api/session.js

updated user home and api session

---

client/store/orders.js
server/api/orders.js

chore: added thunk to update session with open order

---

client/components/order-list.js
client/components/user-home.js
client/store/orders.js

updated user-home order list

---

client/components/user-home.js
client/store/orders.js

updated user-home thunk

---

client/components/auth-form.js
client/components/cart-edit.js
client/components/flower-single.js
client/components/not-found.js
client/components/user-home.js
client/store/index.js
client/store/orders.js
client/store/user.js
server/api/flowers.spec.js
server/api/routProtection.js
server/api/session.js
server/db/models/flower.js
server/db/models/orderFlower.js

clearn up commented out code and console logs

---

public/index.html
server/api/routProtection.js
server/api/users.js
server/db/models/index.js
server/db/models/user.js

Feature: secure user creation

---

client/components/cart.js
client/components/order-list.js
client/store/orders.js
server/api/orders.js

chore: get open cart at user log-in

---

client/components/user-home.js
client/store/orders.js

chore: removed console logs

---

client/components/auth-form.js
client/components/navbar.js
client/components/user-home.js
client/store/orders.js
server/auth/index.js

remove logs
